"""launch_auth_review_and_ci_policy"""
from alembic import op
import sqlalchemy as sa

revision = '621566905b19'
down_revision = '97acccf82c48'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=True),
    sa.Column('grant_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_credentials_grant_id'), 'api_credentials', ['grant_id'], unique=False)
    op.create_index(op.f('ix_api_credentials_user_id'), 'api_credentials', ['user_id'], unique=False)
    op.create_table('browser_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    op.create_table('github_login_states',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cookie_hash', sa.String(length=64), nullable=False),
    sa.Column('verifier', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('review_work_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'head_sha', 'slot_index')
    )
    op.create_index(op.f('ix_review_work_items_submission_id'), 'review_work_items', ['submission_id'], unique=False)
    op.create_table('finding_resolutions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('finding_index', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('resolver_role', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'finding_index')
    )
    op.create_table('review_leases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('work_item_id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['review_work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_review_leases_submission_id'), 'review_leases', ['submission_id'], unique=False)
    op.create_index('uq_active_review_work_lease', 'review_leases', ['work_item_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('uq_active_reviewer_head_lease', 'review_leases', ['submission_id', 'head_sha', 'reviewer_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.add_column('projects', sa.Column('maintainer_id', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('submitted_by', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('required_checks', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.alter_column('projects', 'required_checks', server_default=None)
    op.create_foreign_key('fk_project_submitted_by', 'projects', 'users', ['submitted_by'], ['id'])
    op.create_foreign_key('fk_project_maintainer', 'projects', 'users', ['maintainer_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=40), nullable=True))
    op.create_unique_constraint('uq_user_github_identity', 'users', ['github_id'])
    op.add_column('webhook_deliveries', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_deliveries', 'last_attempt_at')
    op.drop_column('webhook_deliveries', 'next_attempt_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_user_github_identity', 'users', type_='unique')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'password_hash')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_project_maintainer', 'projects', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_project_submitted_by', 'projects', type_='foreignkey')
    op.drop_column('projects', 'required_checks')
    op.drop_column('projects', 'submitted_by')
    op.drop_column('projects', 'maintainer_id')
    op.drop_index('uq_active_reviewer_head_lease', table_name='review_leases', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('uq_active_review_work_lease', table_name='review_leases', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_review_leases_submission_id'), table_name='review_leases')
    op.drop_table('review_leases')
    op.drop_table('finding_resolutions')
    op.drop_index(op.f('ix_review_work_items_submission_id'), table_name='review_work_items')
    op.drop_table('review_work_items')
    op.drop_table('oauth_grants')
    op.drop_table('github_login_states')
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.drop_index(op.f('ix_api_credentials_user_id'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_grant_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
